import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  bar: [
      {
          type: 'link',
          label: 'Paper',
          href: 'https://papermc.io/',
      },
      {
          type: 'link',
          label: 'Purpur',
          href: 'https://purpurmc.org/',
      },
      {
          type: 'link',
          label: 'ApexHosting',
          href: 'https://billing.apexminecrafthosting.com/aff.php?aff=5511',
      },
      {
        type: 'autogenerated', dirName: '.'
      },
  ],
};

export default sidebars;
