/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the v1 folder structure
  crazySidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;